version: '3.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - ZIPKIN_HOST=http://zipkin:9411/api/v2/spans
    networks:
      - my-network
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin:2
    ports:
      - '9411:9411'
    networks:
      - my-network

networks:
  my-network: